package cloud.tteams.identity.user.domain.soap;

public record Ciudadano(
                String nui,
                String nombre,
                String apellidos,
                String nombres,
                String codigoSexo,
                String sexo,
                String fechaNacimiento,
                String fechaCedulacion,
                String fechaActualizacion,
                String codigoInstruccion,
                String instruccion,
                String codigoProfesion,
                String profesion,
                String codigoNacionalidad,
                String nacionalidad,
                String codigoCondicionCedulado,
                String condicionCedulado,
                String codigoEstadoCivil,
                String estadoCivil,
                String codigoGrupoEtnico,
                String grupoEtnico,
                String codigoTipoCedula,
                String tipoCedula,
                String codigoCondicionDonante,
                String condicionDonante,
                String individualDactilar,
                String observacion,
                String firmaElectronica,
                Byte[] fotografia,
                Byte[] firma,
                String nuiPadre,
                String nombrePadre,
                String codigoNacionalidadPadre,
                String nacionalidadPadre,
                String nuiMadre,
                String nombreMadre,
                String codigoNacionalidadMadre,
                String nacionalidadMadre,
                Domicilio domicilio,
                Nacimiento nacimiento,
                Conyuge conyuge,
                Genero genero,
                Defuncion defuncion,
                String organos,
                String fechaOrganos) {

}
