version: '3.7'
services:
  #Cloudservices
  # Postgres
  postgres-db:
    image: postgres:14-alpine
    container_name: postgres-db
    restart: unless-stopped
    hostname: postgres-db
    networks:
      - tteams_internal
      - ev_bridge
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: unless-stopped
    hostname: zookeeper
    networks:
      - tteams_internal
      - ev_bridge
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  # Kafka
  kafka:
      image: confluentinc/cp-kafka:latest
      container_name: kafka
      restart: unless-stopped
      hostname: kafka
      networks:
        - tteams_internal
        - ev_bridge
      depends_on:
        - zookeeper
      ports:
        - 29092:29092
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
networks:
  tteams_internal:
  ev_bridge:
    driver: bridge
