version: '3.7'
services:
  #Cloudservices
  #Spring Cloud Config
  config-service:
    build:
      context: src/cloudservices/config
      dockerfile: Dockerfile
    image: rivasb/tteams-config:v1
    container_name: config
    restart: unless-stopped
    hostname: config
    networks:
      - tteams_internal
    ports:
      - "8081:8081"
  # Netflix Eureka Server
  registry-service:
    build:
      context: src/cloudservices/registry
      dockerfile: Dockerfile
    image: rivasb/tteams-registry:v1
    container_name: registry
    restart: unless-stopped
    hostname: registry
    depends_on:
      - config-service
    networks:
      - tteams_internal
    ports:
      - "8099:8099"
  # Spring Cloud Gateway
  gateway-service:
    build:
      context: src/cloudservices/gateway
      dockerfile: Dockerfile
    image: rivasb/tteams-gateway:v1
    container_name: gateway
    restart: unless-stopped
    hostname: gateway
    depends_on:
      - config-service
      - registry-service
    networks:
      - tteams_internal
      - ev_bridge
    ports:
      - "8091:8091"
  # Microservices
  # Identity
  identity-service:
    build:
      context: src/microservices/identity
      dockerfile: Dockerfile
    image: rivasb/tteams-identity:v1
    container_name: identity
    restart: unless-stopped
    hostname: identity
    depends_on:
      - config-service
      - registry-service
      - gateway-service
      - postgres-db
    networks:
      - tteams_internal
    ports:
      - "8083:8083"
  # Station
  station-service:
    build:
      context: src/microservices/project
      dockerfile: Dockerfile
    image: rivasb/tteams-station:v1
    container_name: project
    restart: unless-stopped
    hostname: project
    depends_on:
      - config-service
      - registry-service
      - gateway-service
      - postgres-db
    networks:
      - tteams_internal
    ports:
      - "8084:8084"
  # Postgres
  postgres-db:
    image: postgres:14-alpine
    container_name: postgres-db
    restart: unless-stopped
    hostname: postgres-db
    networks:
      - tteams_internal
      - ev_bridge
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  # Mysql
  mysql-db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-db
    restart: unless-stopped
    hostname: mysql-db
    networks:
      - tteams_internal
      - ev_bridge
    environment:
      MYSQL_ROOT_PASSWORD: S3cr3tp4sword
      MYSQL_DATABASE: ev-project
      MYSQL_USER: db_user
      MYSQL_PASSWORD: S3cr3tp4sword
    ports:
      - 3306:3306
  # Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: unless-stopped
    hostname: zookeeper
    networks:
      - tteams_internal
      - ev_bridge
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  # Kafka
  kafka:
      image: confluentinc/cp-kafka:latest
      container_name: kafka
      restart: unless-stopped
      hostname: kafka
      networks:
        - tteams_internal
        - ev_bridge
      depends_on:
        - zookeeper
      ports:
        - 29092:29092
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
networks:
  tteams_internal:
  ev_bridge:
    driver: bridge
