# [Optional]Aplication server port
server:
  port: 8087

spring:
  application:
    name: comment
  jpa:
    database: default
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create

  # [Required]PostgreSQL Write database data source
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${POSTGRES_DB_URL}/${POSTGRES_DB_COMMENT}
    username: ${POSTGRES_DB_USERNAME}
    password: ${POSTGRES_DB_PASSWORD}

  # [Required]PostgreSQL Read database data source
  read-datasource:
    driverClassName: org.postgresql.Driver
    url: ${POSTGRES_DB_URL}/${POSTGRES_DB_COMMENT}
    username: ${POSTGRES_DB_USERNAME}
    password: ${POSTGRES_DB_PASSWORD}

  # [Required]Swagger issue configuration
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    # Custom Handle for NoHandlerFoundException
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

  # Mail server configuration
  mail:
    active: ${MAIL_HOST_ACTIVE}

# Propiedad separada en el archivo .properties original
hibernate:
  hbm2ddl:
    auto: update

logging:
  level:
    org.hibernate.engine.jdbc.connections.internal: DEBUG

# Kafka
kafka:
  bootstrap:
    address: ${KAFKA_BOOTSTRAP_ADDRESS}
  # KafkaMessengers
  messenger:
    comment: true

# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
  instance:
    preferIpAddress: true