# [Optional]Application server port
server:
  port: 8083

spring:
  application:
    name: identity
  main:
    allow-bean-definition-overriding: true
  jpa:
    database: default
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

  # [Required]PostgreSQL Write database data source
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${POSTGRES_DB_URL}/${POSTGRES_DB_IDENTITY}
    username: ${POSTGRES_DB_USERNAME}
    password: ${POSTGRES_DB_PASSWORD}

  # [Required]Swagger issue configuration
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    # Custom Handle for NoHandlerFoundException
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

  # Configuracion del servidor de correo
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

# Propiedad separada en el archivo .properties original
hibernate:
  hbm2ddl:
    auto: update

logging:
  level:
    org.hibernate.engine.jdbc.connections.internal: DEBUG

# [Required]JWT configuration
security:
  jwt:
    header:
      string: ${JWT_HEADER_STRING}
    token:
      prefix: ${JWT_TOKEN_PREFIX}
    secret: ${JWT_SECRET}
    issuer: ${JWT_ISSUER}
    ttlMillis: ${JWT_TTL_MILLIS}
    authorities:
      key: ${JWT_AUTHORITIES_KEY}

# Kafka
kafka:
  bootstrap:
    address: ${KAFKA_BOOTSTRAP_ADDRESS}
  # KafkaMessengers
  messenger:
    user: false
    organization: false
    location: false

# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
  instance:
    preferIpAddress: true