server:
  port: 8085

spring:
  application:
    name: log
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create


  data:
    mongodb:
      uri: mongodb://${MONGODB_HOST}:${MONGODB_PORT}/${LOG_DATABASE}
      database: ${LOG_DATABASE}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    # Custom Handle for NoHandlerFoundException
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

  # Mail server configuration
  mail:
    active: ${MAIL_HOST_ACTIVE}

  # [Required]Kafka consumer configuration
  kafka:
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"


# Propiedad separada en el archivo '.properties' original
hibernate:
  hbm2ddl:
    auto: update

logging:
  level:
    org.hibernate.engine.jdbc.connections.internal: DEBUG

# Kafka
kafka:
  bootstrap:
    address: ${KAFKA_BOOTSTRAP_ADDRESS}



# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
  instance:
    preferIpAddress: true