package ec.gob.registrocivil.share.middleware.certificationsimple.domain;

public enum TypeCertification {
    SERVICE_CERTIFICADO_NACIMIENTO,
    SERVICE_CERTIFICADO_MATRIMONIO,
    SERVICE_CERTIFICADO_UNION_HECHO,
    SERVICE_CERTIFICADO_DEFUNCION,
    SERVICE_CERTIFICADO_GENERO,
    SERVICE_CERTIFICADO_IDENTIDAD_ESTADO_CIVIL,
}
