name: ci-share

on:
  push:
    branches:
      - 'dev'
    paths:
      - .github/workflows/share.yml
      - src/microservices/share/**

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Publish package
        run: cd src/microservices/share && mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }}